import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import ScrollUp from '@/components/ScrollUp'
import FadeAnimationHandle from '@/components/FadeAnimationHandle'
import Footer from '@/components/Footer'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Toaster />
                <Navbar />
                <ScrollUp />
                <FadeAnimationHandle />
                {children}
                <Footer />
            </body>
        </html>
    )
}
